apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcverifier.fullname" . }}
  labels:
    {{- include "vcverifier.labels" . | nindent 4 }}
data:
  server.yaml: |-
    server:
      listenAddress: "0.0.0.0:{{ .Values.deployment.port }}"
      staticDir: "back/www"
      templateDir: "back/views"
      environment: development
      loglevel: {{ .Values.deployment.logLevel }}

    store:
      driverName: {{ .Values.db.store.driver | quote }}
      dataSourceName: {{ .Values.db.store.connectionString | quote }}

    verifier:
      id: PacketDelivery
      name: PacketDelivery
      password: ThePassword
      uri_prefix: /verifier
      jwks_uri: /.well-known/jwks
      store:
        driverName: {{ .Values.db.verifier.driver | quote }}
        dataSourceName: {{ .Values.db.verifier.connectionString | quote }}
      protectedResource:
        url: "{{ .Values.deployment.protectedResource }}"

    verifiableregistry:
      password: ThePassword
      store:
        driverName: {{ .Values.db.verifiableregistry.driver | quote }}
        dataSourceName: {{ .Values.db.verifiableregistry.connectionString | quote }}

    ssikit:
      coreURL: {{ .Values.deployment.walt.coreUrl }}
      signatoryURL: {{ .Values.deployment.walt.signatoryUrl }}
      auditorURL: {{ .Values.deployment.walt.auditorUrl }}
      custodianURL: {{ .Values.deployment.walt.custodianUrl }}
      essifURL: {{ .Values.deployment.walt.essifUrl }}
