apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcverifier.fullname" . }}
  labels:
    {{- include "vcverifier.labels" . | nindent 4 }}
data:
  server.yaml: |-
    server:
      host: {{ .Values.deployment.server.host | quote }}
      port: {{ .Values.deployment.port }}
      staticDir: {{ .Values.deployment.server.staticDir | quote }}
      templateDir: {{ .Values.deployment.server.templateDir | quote }}
    m2m:
      authEnabled: {{ .Values.deployment.m2m.authEnabled }}
      keyPath: {{ .Values.deployment.m2m.keyPath }}
      credentialPath: {{ .Values.deployment.m2m.credentialPath }}
      verificationMethod: {{ .Values.deployment.m2m.verificationMethod }}  
    logging:
      level: {{ .Values.deployment.logging.level | quote }}
      jsonLogging: {{ .Values.deployment.logging.jsonLogging | quote }}
      logRequests: {{ .Values.deployment.logging.logRequests | quote }}
      pathsToSkip: {{ .Values.deployment.logging.pathsToSkip }}

    verifier:
      did: {{ .Values.deployment.verifier.did | quote }}
      tirAddress: {{ .Values.deployment.verifier.tirAddress | quote }}
      sessionExpiry: {{ .Values.deployment.verifier.sessionExpiry }}

    ssiKit:
      auditorURL: {{ .Values.deployment.ssikit.auditorUrl }}
    
    configRepo:
      {{- with .Values.deployment.configRepo }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
