apiVersion: v1
name: mvf
version: 1.1.0
appVersion: 1.1.1
home: https://github.com/hesusruiz/mvf
description: A Helm chart for running the i4Trust DSBA mvf.
keywords:
- i4Trust
- experimentation framework
- proof of concept
- verifiable credentials
maintainers:
- name: wistefan
  email: stefan.wiedemann@fiware.org
  
