apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcbackend.fullname" . }}
  labels:
    {{- include "vcbackend.labels" . | nindent 4 }}
data:
  server.yaml: |-
    server:
      listenAddress: "0.0.0.0:{{ .Values.deployment.port }}"
      staticDir: "back/www"
      templateDir: "back/views"
      environment: development
      loglevel: {{ .Values.deployment.logLevel }}

    store:
      driverName: "sqlite3"
      dataSourceName: "file:/db/issuer.sqlite?mode=rwc&cache=shared&_fk=1"

    issuer:
      id: HappyPets
      name: HappyPets
      password: ThePassword
      store:
        driverName: "sqlite3"
        dataSourceName: "file:/db/issuer.sqlite?mode=rwc&cache=shared&_fk=1"

    verifier:
      id: PacketDelivery
      name: PacketDelivery
      password: ThePassword
      store:
        driverName: "sqlite3"
        dataSourceName: "file:/db/verifier.sqlite?mode=rwc&cache=shared&_fk=1"
      protectedResource:
        url: "{{ .Values.deployment.protectedResource }}"

    verifiableregistry:
      password: ThePassword
      store:
        driverName: "sqlite3"
        dataSourceName: "file:/db/verifiableregistry.sqlite?mode=rwc&cache=shared&_fk=1"

    wallet:
      store:
        driverName: "sqlite3"
        dataSourceName: "file:/db/wallet.sqlite?mode=rwc&cache=shared&_fk=1"

    ssikit:
      coreURL: {{ .Values.deployment.walt.coreUrl }}
      signatoryURL: {{ .Values.deployment.walt.signatoryUrl }}
      auditorURL: {{ .Values.deployment.walt.auditorUrl }}
      custodianURL: {{ .Values.deployment.walt.custodianUrl }}
      essifURL: {{ .Values.deployment.walt.essifUrl }}

    webauthn:
      RPDisplayName: "Gaia-X AISBL"
      RPID: "localhost"
      RPOrigin: "http://localhost:3000"
      AuthenticatorAttachment: "platform"
      UserVerification: "required"

