kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "vcbackend.fullname" . }}
  labels:
    {{ include "vcbackend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vcbackend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "vcbackend.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec: 
      serviceAccountName: {{ include "vcbackend.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
              name: backend
          env:
            - name: CONFIG_FILE
              value: /configs/server.yaml
          {{- if .Values.deployment.additionalEnvVars }}
            {{- with .Values.deployment.additionalEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          ## workaround for missing db support
          volumeMounts:
            - mountPath: /configs/
              name: config-volume
            {{- if .Values.deployment.sqlite }}
            - mountPath: /db/
              name: db-volume
            {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "vcbackend.fullname" . }}
      {{- if .Values.deployment.sqlite }}
      - name: db-volume
        persistentVolumeClaim:
          claimName: {{ include "vcbackend.fullname" . }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}