apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdc-portal.fullname" . }}
  labels:
    {{- include "pdc-portal.labels" . | nindent 4 }}
data:
  pdc-portal.yml: |-
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- if .Values.ccs.endpoint -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdc-portal.fullname" . }}-ccs
  labels:
    {{- include "pdc-portal.labels" . | nindent 4 }}
data:
  init.sh: |-
    curl -X 'POST' \
      '{{ .Values.ccs.url }}service' \
      -H 'accept: */*' \
      -H 'Content-Type: application/json' \
      -d '{
      "id": "{{ .Values.ccs.id }}",
      "credentials": {{- toJson .Values.ccs.credentials }}
    }'
{{- end }}