apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdc-portal.fullname" . }}
  labels:
    {{- include "pdc-portal.labels" . | nindent 4 }}
data:
  pdc-portal.yml: |-
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
