apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcwaltid.fullname" . }}-sm
  labels:
    {{- include "vcwaltid.labels" . | nindent 4 }}
data:
  service-matrix.properties: |
    {{- with .Values.config.serviceMatrix }}
    {{- . | nindent 4 }}
    {{- end }}