apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcwaltid.fullname" . }}-templates
  labels:
    {{- include "vcwaltid.labels" . | nindent 4 }}
data:
  {{- with .Values.templates }}
  {{- toYaml . | nindent 2 }}
  {{- end }}