kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "vcwaltid.fullname" . }}
  labels:
    {{ include "vcwaltid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vcwaltid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "vcwaltid.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec: 
      serviceAccountName: {{ include "vcwaltid.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          args:
            - serve
            - -b
            - 0.0.0.0
          ports:
            {{- if .Values.api.core.enabled }}
            - containerPort: {{ .Values.api.core.port }}
              name: core-api
            {{- end}}
            {{- if .Values.api.signatory.enabled }}
            - containerPort: {{ .Values.api.signatory.port }}
              name: signatory-api
            {{- end}}
            {{- if .Values.api.custodian.enabled }}
            - containerPort: {{ .Values.api.custodian.port }}
              name: custodian-api
            {{- end}}
            {{- if .Values.api.auditor.enabled }}
            - containerPort: {{ .Values.api.auditor.port }}
              name: auditor-api
            {{- end}}
            {{- if .Values.api.essif.enabled }}
            - containerPort: {{ .Values.api.essif.port }}
              name: essif-api
            {{- end}}
          {{- if .Values.additionalEnvVars }}
          env:
            {{- with .Values.additionalEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          ## workaround for missing db support
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
            - mountPath: /templates
              name: templates-volume
            - mountPath: /app
              name: config-volume
      volumes:
      - name: data-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: config-volume
        configMap:
          name: {{ include "vcwaltid.fullname" . }}
      - name: templates-volume
        configMap:
          name: {{ include "vcwaltid.fullname" . }}-templates
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}