apiVersion: v1
kind: Service
metadata:
  name: {{ include "vcwaltid.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{ include "vcwaltid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.api.core.enabled }}
    - name: http-core
      port: {{ .Values.api.core.port }}
      targetPort: core-api
      protocol: TCP
    {{- end}}
    {{- if .Values.api.signatory.enabled }}
    - name: http-signatory
      port: {{ .Values.api.signatory.port }}
      targetPort: signatory-api
      protocol: TCP
    {{- end}}
    {{- if .Values.api.custodian.enabled }}
    - name: http-custodian
      port: {{ .Values.api.custodian.port }}
      targetPort: custodian-api
      protocol: TCP
    {{- end}}
    {{- if .Values.api.auditor.enabled }}
    - name: http-auditor
      port: {{ .Values.api.auditor.port }}
      targetPort: auditor-api
      protocol: TCP
    {{- end}}
    {{- if .Values.api.essif.enabled }}
    - name: http-essif
      port: {{ .Values.api.essif.port }}
      targetPort: essif-api
      protocol: TCP
    {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "vcwaltid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}