apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activation-service.fullname" . }}
  labels:
    {{- include "activation-service.labels" . | nindent 4 }}
data:
  as.yml: |-
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- if .Values.ccs.endpoint -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activation-service.fullname" . }}-ccs
  labels:
    {{- include "activation-service.labels" . | nindent 4 }}
data:
  init.sh: |-
    curl -X 'POST' \
      '{{ .Values.ccs.endpoint }}service' \
      -H 'accept: */*' \
      -H 'Content-Type: application/json' \
      -d '{
      "id": "{{ .Values.ccs.id }}",
      "default_scope": "{{ .Values.ccs.defaultScope }}",
      {{- if .Values.ccs.scopes -}}
      "scopes": {{- toJson .Values.ccs.scopes }}
      {{- end }}
    }'
{{- end }}
