name: Chart Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  # lint the charts
  lint:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: ./lint.sh

  eval:

    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: Eval
        run: |
          .github/build/install.sh
          ./eval.sh
